// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _202503271248391_UniDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202503271248391_UniDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202506030904229_202503271248391_UniDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
